// App
export const INIT = 'INIT';
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

// EXERCISES
export const EXERCISES_GET = 'EXERCISES_GET';
export const EXERCISES_UPDATE = 'EXERCISES_UPDATE';
export const EXERCISE_SOURCES_UPDATE = 'EXERCISE_SOURCES_UPDATE';
export const UPDATE_EDIT_EXERCISE_STATE = 'UPDATE_EDIT_EXERCISE_STATE';

// SOLUTIONS
export const SOLUTION_UPDATE = 'SOLUTION_UPDATE';
export const SOLUTIONS_UPDATE = 'SOLUTIONS_UPDATE';
export const SOLUTION_SOURCES_UPDATE = 'SOLUTION_SOURCES_UPDATE';
export const SOLUTION_DELETE_SOURCE_FILE = 'SOLUTION_DELETE_SOURCE_FILE';
export const SOLVE_ATTEMPTS_UPDATE = 'SOLVE_ATTEMPTS_UPDATE';
export const NEW_SOLVE_ATTEMPT = 'NEW_SOLVE_ATTEMPT';

// NOTIFICATION
export const NOTIFICATION = 'NOTIFICATION';
export const SET_CONFIRMATION = 'SET_CONFIRMATION';

// USER
export const USER_UPDATE = 'USER_UPDATE';

// USER SESSION
export const SESSION_AUTH_UPDATE = 'SESSION_AUTH_UPDATE';
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_GET = 'SESSION_GET';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_REDIRECT_TO_LOGIN = 'SESSION_REDIRECT_TO_LOGIN';

// ExerciseManager
export const EXERCISE_MANAGER_NEW = 'EXERCISE_MANAGER_NEW';
export const EXERCISE_MANAGER_DELETE = 'EXERCISE_MANAGER_DELETE';

// ExerciseEditor
export const EXERCISE_EDITOR_CHANGE_TAB = 'EXERCISE_EDITOR_CHANGE_TAB';
export const EXERCISE_EDITOR_SET_CURRENT_FILE = 'EXERCISE_EDITOR_SET_CURRENT_FILE';
export const EXERCISE_EDITOR_PROPERTIES_UPDATE = 'EXERCISE_EDITOR_PROPERTIES_UPDATE';
export const EXERCISE_EDITOR_PROPERTIES_UPDATE_FROM_SERVER = 'EXERCISE_EDITOR_PROPERTIES_UPDATE_FROM_SERVER';
export const EXERCISE_EDITOR_SET_PROPERTIES_FEEDBACK = 'EXERCISE_EDITOR_SET_PROPERTIES_FEEDBAC';
export const EXERCISE_EDITOR_SAVE_PROPERTIES = 'EXERCISE_EDITOR_SAVE_PROPERTIES';
export const EXERCISE_EDITOR_SOURCE_FILES_UPDATE_FROM_SERVER = 'EXERCISE_EDITOR_SOURCE_FILES_UPDATE_FROM_SERVER_FROM_SERVER';
export const EXERCISE_EDITOR_SOURCE_FILE_UPDATE = 'EXERCISE_EDITOR_SOURCE_FILE_UPDATE';
export const EXERCISE_EDITOR_SOURCE_FILE_UPDATE_FROM_SERVER = 'EXERCISE_EDITOR_SOURCE_FILE_UPDATE_FROM_SERVER';
export const EXERCISE_EDITOR_SOURCE_FILE_SAVE = 'EXERCISE_EDITOR_SOURCE_FILE_SAVE';
export const EXERCISE_EDITOR_SOURCE_FILE_CREATE_NEW = 'EXERCISE_EDITOR_SOURCE_FILE_CREATE_NEW';
export const EXERCISE_EDITOR_SOURCE_FILE_DELETE = 'EXERCISE_EDITOR_SOURCE_FILE_DELETE';
export const EXERCISE_EDITOR_RENAME_CURRENT_FILE_UPDATE = 'EXERCISE_EDITOR_RENAME_CURRENT_FILE_UPDATE';
export const EXERCISE_EDITOR_RENAME_CURRENT_FILE_OK = 'EXERCISE_EDITOR_RENAME_CURRENT_FILE_OK';
