// EXERCISES
export const EXERCISES_UPDATE = 'EXERCISES_UPDATE';
export const EXERCISE_SOURCES_UPDATE = 'EXERCISE_SOURCES_UPDATE';
export const UPDATE_EDIT_EXERCISE_STATE = 'UPDATE_EDIT_EXERCISE_STATE';

// SOLUTIONS
export const SOLUTION_UPDATE = 'SOLUTION_UPDATE';
export const SOLUTIONS_UPDATE = 'SOLUTIONS_UPDATE';
export const SOLUTION_SOURCES_UPDATE = 'SOLUTION_SOURCES_UPDATE';
export const SOLUTION_DELETE_SOURCE_FILE = 'SOLUTION_DELETE_SOURCE_FILE';
export const SOLVE_ATTEMPTS_UPDATE = 'SOLVE_ATTEMPTS_UPDATE';
export const NEW_SOLVE_ATTEMPT = 'NEW_SOLVE_ATTEMPT';

// NOTIFICATION
export const NOTIFICATION = 'NOTIFICATION';
export const SET_CONFIRMATION = 'SET_CONFIRMATION';

// USER
export const USER_UPDATE = 'USER_UPDATE';
export const USER_AUTH_UPDATE = 'USER_AUTH_UPDATE';

// USER SESSION
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_GET = 'SESSION_GET';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';