'use strict';

var PREFIX = 'USER_CONSTANTS_';

module.exports = {
  USER_UPDATE_FROM_SERVER: PREFIX + 'USER_UPDATE_FROM_SERVER',
  USER_AUTH_UPDATE_FROM_SERVER: PREFIX + 'USER_AUTH_UPDATE_FROM_SERVER'
};
