'use strict';

var PREFIX = 'ADMIN_USERS_STORE_';

module.exports = {
  USERS_UPDATE_FROM_SERVER: PREFIX + 'USERS_UPDATE_FROM_SERVER',
  CLOSE_EDIT_USER: PREFIX + 'CLOSE_EDIT_USER',
  EDIT_USER: PREFIX + 'EDIT_USER',
  SAVE_USER: PREFIX + 'SAVE_USER',
  INVALID_USER_DATA: PREFIX + 'INVALID_USER_DATA'
};
